---
# This is a sample database file for the ActiveRecord ORM
:development: &defaults
  :adapter: mysql
  :database: panda_development
  :username: root
  :password: 
  :host: localhost
  :encoding: utf8
  
:test:
  <<: *defaults
  :database: sample_test

:production:
  <<: *defaults
  :database: panda_production
  
:rake:
  <<: *defaults